blank_issues_enabled: false
contact_links:
  - name: Open edX Community Support
    url: https://discuss.openedx.org/
    about: Please ask and answer questions here.
  - name: Report a Security Vulnerability
    url: https://www.edx.org/policy/security
    about: Please report security vulnerabilities here.